//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.CustomerOrders = new HashSet<CustomerOrders>();
            this.Find_Quotations = new HashSet<Find_Quotations>();
            this.Quotations = new HashSet<Quotations>();
            this.TempQuotations = new HashSet<TempQuotations>();
            this.ProductionOrders = new HashSet<ProductionOrders>();
        }
    
        public int Code { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Street { get; set; }
        public string CAP { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string P_IVA { get; set; }
        public string Note { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> IDAgente1 { get; set; }
        public string DescrizioneAgente1 { get; set; }
    
        public virtual ICollection<CustomerOrders> CustomerOrders { get; set; }
        public virtual CustomersMarkUps CustomersMarkUps { get; set; }
        public virtual ICollection<Find_Quotations> Find_Quotations { get; set; }
        public virtual ICollection<Quotations> Quotations { get; set; }
        public virtual ICollection<TempQuotations> TempQuotations { get; set; }
        public virtual ICollection<ProductionOrders> ProductionOrders { get; set; }
    }
}
