//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependencies
    {
        public int Id { get; set; }
        public Nullable<int> LinkCode { get; set; }
        public string Link { get; set; }
        public string Dependent { get; set; }
    
        public virtual Links Links { get; set; }
    }
}
