//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Employees1 = new HashSet<Employees>();
            this.Find_Quotations = new HashSet<Find_Quotations>();
            this.Quotations = new HashSet<Quotations>();
            this.Quotations1 = new HashSet<Quotations>();
            this.TempQuotations = new HashSet<TempQuotations>();
            this.TempQuotations1 = new HashSet<TempQuotations>();
            this.CloseOfDays = new HashSet<CloseOfDays>();
            this.ProductionOrderDetails = new HashSet<ProductionOrderDetails>();
            this.ProductionOrderTechSpecs = new HashSet<ProductionOrderTechSpecs>();
            this.ProductionOrders = new HashSet<ProductionOrders>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<int> ID_Manager { get; set; }
        public Nullable<int> ID_Dept { get; set; }
        public Nullable<int> ID_Machine { get; set; }
        public string UniqueName { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public Nullable<short> Role { get; set; }
        public Nullable<int> ID_Company { get; set; }
    
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        public virtual ICollection<Find_Quotations> Find_Quotations { get; set; }
        public virtual ICollection<Quotations> Quotations { get; set; }
        public virtual ICollection<Quotations> Quotations1 { get; set; }
        public virtual ICollection<TempQuotations> TempQuotations { get; set; }
        public virtual ICollection<TempQuotations> TempQuotations1 { get; set; }
        public virtual ICollection<CloseOfDays> CloseOfDays { get; set; }
        public virtual ICollection<ProductionOrderDetails> ProductionOrderDetails { get; set; }
        public virtual ICollection<ProductionOrderTechSpecs> ProductionOrderTechSpecs { get; set; }
        public virtual ICollection<ProductionOrders> ProductionOrders { get; set; }
    }
}
