//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Find_QuotationTemplates
    {
        public int ID { get; set; }
        public Nullable<int> ID_QuotationTemplate { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeCode { get; set; }
        public Nullable<int> ItemTypeCode { get; set; }
    }
}
