//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFieldMappingInfo
    {
        public int ID { get; set; }
        public string OriginTableName { get; set; }
        public string DestTableName { get; set; }
        public string OriginFieldName { get; set; }
        public string DestFieldName { get; set; }
    }
}
