//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacroItemDetails
    {
        public int ID { get; set; }
        public int ID_MacroItem { get; set; }
        public string Position { get; set; }
        public int CommonKey { get; set; }
        public float Quantity { get; set; }
        public bool Inserted { get; set; }
        public bool Multiply { get; set; }
        public bool SelectPhase { get; set; }
        public string Link { get; set; }
    
        public virtual MacroItems MacroItems { get; set; }
        public virtual PickingItems PickingItems { get; set; }
    }
}
