//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickingItems
    {
        public PickingItems()
        {
            this.MacroItemDetails = new HashSet<MacroItemDetails>();
            this.QuotationDetails = new HashSet<QuotationDetails>();
            this.QuotationTemplateDetails = new HashSet<QuotationTemplateDetails>();
            this.TempQuotationDetails = new HashSet<TempQuotationDetails>();
            this.ProductionOrderTechSpecs = new HashSet<ProductionOrderTechSpecs>();
        }
    
        public int ID { get; set; }
        public int TypeCode { get; set; }
        public int ItemTypeCode { get; set; }
        public string ItemDescription { get; set; }
        public int UM { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public bool Inserted { get; set; }
        public bool Multiply { get; set; }
        public int Percentage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Link { get; set; }
        public string MILink { get; set; }
        public string Order { get; set; }
        public Nullable<int> Template { get; set; }
        public Nullable<int> ItemManufacturing { get; set; }
        public Nullable<int> StandardPercentageCode { get; set; }
        public string Note { get; set; }
        public Nullable<int> ID_Company { get; set; }
    
        public virtual ItemDisplayModes ItemDisplayModes { get; set; }
        public virtual ItemTypes ItemTypes { get; set; }
        public virtual ICollection<MacroItemDetails> MacroItemDetails { get; set; }
        public virtual StandardPercentages StandardPercentages { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Types Types { get; set; }
        public virtual Units Units { get; set; }
        public virtual ICollection<QuotationDetails> QuotationDetails { get; set; }
        public virtual ICollection<QuotationTemplateDetails> QuotationTemplateDetails { get; set; }
        public virtual ICollection<TempQuotationDetails> TempQuotationDetails { get; set; }
        public virtual ICollection<ProductionOrderTechSpecs> ProductionOrderTechSpecs { get; set; }
    }
}
