//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrderTechSpecs
    {
        public int ID { get; set; }
        public Nullable<int> ID_ProductionOrder { get; set; }
        public Nullable<int> ID_ProductionOrderDetail { get; set; }
        public Nullable<int> ID_QuotationDetail { get; set; }
        public Nullable<int> ID_Owner { get; set; }
        public Nullable<int> ID_Phase { get; set; }
        public string CodiceMarcaFilm { get; set; }
        public string ClicheReso { get; set; }
        public string ClicheCondizioni { get; set; }
        public string StampaTemperatura { get; set; }
        public string AltreInfo { get; set; }
        public string CodiceMarcaInchiostro { get; set; }
        public Nullable<bool> Ricetta { get; set; }
        public string TelaioNumeroFili { get; set; }
        public string GelatinaSpessore { get; set; }
        public string RaclaInclinazione { get; set; }
        public string RaclaDurezzaSpigolo { get; set; }
        public string FustellaResa { get; set; }
        public string FustellaCondizioni { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public string AltreNoteDaProduzione { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual PickingItems PickingItems { get; set; }
        public virtual ProductionOrderDetails ProductionOrderDetails { get; set; }
        public virtual QuotationDetails QuotationDetails { get; set; }
        public virtual ProductionOrders ProductionOrders { get; set; }
    }
}
