//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrderDetails
    {
        public ProductionOrderDetails()
        {
            this.ProductionOrderTechSpecs = new HashSet<ProductionOrderTechSpecs>();
        }
    
        public int ID { get; set; }
        public int ID_ProductionOrder { get; set; }
        public Nullable<int> ID_QuotationDetail { get; set; }
        public Nullable<int> ID_Owner { get; set; }
        public Nullable<int> ID_PickingItem { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public Nullable<int> UMRawMaterial { get; set; }
        public Nullable<int> UMUser { get; set; }
        public Nullable<int> ID_PickingItemSup { get; set; }
        public Nullable<int> SupplierCodeSup { get; set; }
        public Nullable<float> RawMaterialX { get; set; }
        public Nullable<float> RawMaterialY { get; set; }
        public Nullable<float> RawMaterialZ { get; set; }
        public Nullable<float> RawMaterialQuantity { get; set; }
        public Nullable<int> ID_Phase { get; set; }
        public Nullable<int> UMProduct { get; set; }
        public Nullable<float> ProducedQuantity { get; set; }
        public Nullable<decimal> ProductionTime { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public bool QuantityOver { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public bool DirectSupply { get; set; }
        public string Note { get; set; }
        public Nullable<int> FreeTypeCode { get; set; }
        public Nullable<int> FreeItemTypeCode { get; set; }
        public string FreeItemDescription { get; set; }
        public string RFlag { get; set; }
        public string SFlag { get; set; }
        public string FFlag { get; set; }
        public Nullable<decimal> HistoricalCostPhase { get; set; }
        public Nullable<decimal> HistoricalCostRawM { get; set; }
        public Nullable<decimal> HistoricalCostSupM { get; set; }
        public Nullable<int> MacroRef { get; set; }
        public Nullable<int> OkCopiesCount { get; set; }
        public Nullable<bool> Special { get; set; }
        public Nullable<System.DateTime> CreateTS { get; set; }
        public Nullable<System.DateTime> UpdateTS { get; set; }
        public Nullable<int> ID_Company { get; set; }
        public Nullable<int> KoCopiesCount { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ItemTypes ItemTypes { get; set; }
        public virtual QuotationDetails QuotationDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Suppliers Suppliers1 { get; set; }
        public virtual Types Types { get; set; }
        public virtual Units Units { get; set; }
        public virtual Units Units1 { get; set; }
        public virtual Units Units2 { get; set; }
        public virtual ICollection<ProductionOrderTechSpecs> ProductionOrderTechSpecs { get; set; }
        public virtual ProductionOrders ProductionOrders { get; set; }
    }
}
