//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationTemplates
    {
        public QuotationTemplates()
        {
            this.QuotationTemplateDetails = new HashSet<QuotationTemplateDetails>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public int TypeCode { get; set; }
        public int ItemTypeCode { get; set; }
        public int UM { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public bool Inserted { get; set; }
        public bool Multiply { get; set; }
        public int Percentage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Link { get; set; }
        public string PILink { get; set; }
        public string Order { get; set; }
        public Nullable<int> Template { get; set; }
        public Nullable<int> ItemManufacturing { get; set; }
        public string Note { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
    
        public virtual ICollection<QuotationTemplateDetails> QuotationTemplateDetails { get; set; }
    }
}
