//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetails
    {
        public QuotationDetails()
        {
            this.ProductionOrderDetails = new HashSet<ProductionOrderDetails>();
            this.ProductionOrderTechSpecs = new HashSet<ProductionOrderTechSpecs>();
        }
    
        public int ID { get; set; }
        public int ID_Quotation { get; set; }
        public string Position { get; set; }
        public int TypeCode { get; set; }
        public Nullable<int> CommonKey { get; set; }
        public Nullable<int> MacroItemKey { get; set; }
        public int ItemTypeCode { get; set; }
        public string ItemTypeDescription { get; set; }
        public int UM { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public float Quantity { get; set; }
        public bool Inserted { get; set; }
        public bool Multiply { get; set; }
        public bool SelectPhase { get; set; }
        public int MarkUp { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public int Percentage { get; set; }
        public bool Save { get; set; }
        public Nullable<int> ID_Company { get; set; }
    
        public virtual ItemTypes ItemTypes { get; set; }
        public virtual MacroItems MacroItems { get; set; }
        public virtual PickingItems PickingItems { get; set; }
        public virtual Quotations Quotations { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Types Types { get; set; }
        public virtual Units Units { get; set; }
        public virtual ICollection<ProductionOrderDetails> ProductionOrderDetails { get; set; }
        public virtual ICollection<ProductionOrderTechSpecs> ProductionOrderTechSpecs { get; set; }
    }
}
