//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTexts
    {
        public int ID { get; set; }
        public int ReportTypeCode { get; set; }
        public int TextTypeCode { get; set; }
        public string Text { get; set; }
        public Nullable<int> ID_Ref01 { get; set; }
        public Nullable<int> ID_Ref02 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Standard { get; set; }
    }
}
