//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectorTypes
    {
        public SelectorTypes()
        {
            this.Selectors = new HashSet<Selectors>();
        }
    
        public int Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Selectors> Selectors { get; set; }
    }
}
