//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selectors
    {
        public int ID { get; set; }
        public Nullable<int> QueryCode { get; set; }
        public Nullable<int> SelectorType { get; set; }
        public Nullable<int> SelectorCode { get; set; }
    
        public virtual Queries Queries { get; set; }
        public virtual SelectorTypes SelectorTypes { get; set; }
    }
}
