//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardPercentages
    {
        public StandardPercentages()
        {
            this.PickingItems = new HashSet<PickingItems>();
        }
    
        public int Code { get; set; }
        public int Percentage { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PickingItems> PickingItems { get; set; }
    }
}
