//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StickingErrors
    {
        public int ID { get; set; }
        public string PhaseType { get; set; }
        public string PhaseDescription { get; set; }
        public string UM { get; set; }
        public Nullable<float> Quantity { get; set; }
        public Nullable<double> Cost1 { get; set; }
        public Nullable<double> Price1 { get; set; }
        public Nullable<double> Cost2 { get; set; }
        public Nullable<double> Price2 { get; set; }
        public Nullable<double> Cost3 { get; set; }
        public Nullable<double> Price3 { get; set; }
    }
}
