//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.PickingItems = new HashSet<PickingItems>();
            this.QuotationDetails = new HashSet<QuotationDetails>();
            this.QuotationTemplateDetails = new HashSet<QuotationTemplateDetails>();
            this.TempQuotationDetails = new HashSet<TempQuotationDetails>();
            this.ProductionOrderDetails = new HashSet<ProductionOrderDetails>();
            this.ProductionOrderDetails1 = new HashSet<ProductionOrderDetails>();
        }
    
        public int Code { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Street { get; set; }
        public string CAP { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string P_IVA { get; set; }
        public string Note { get; set; }
        public Nullable<int> MarkUp { get; set; }
        public string Name2 { get; set; }
    
        public virtual ICollection<PickingItems> PickingItems { get; set; }
        public virtual ICollection<QuotationDetails> QuotationDetails { get; set; }
        public virtual ICollection<QuotationTemplateDetails> QuotationTemplateDetails { get; set; }
        public virtual ICollection<TempQuotationDetails> TempQuotationDetails { get; set; }
        public virtual ICollection<ProductionOrderDetails> ProductionOrderDetails { get; set; }
        public virtual ICollection<ProductionOrderDetails> ProductionOrderDetails1 { get; set; }
    }
}
