//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConverters
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int ID_UserUnit { get; set; }
        public int ID_FinalUnit { get; set; }
        public int Quotient { get; set; }
    
        public virtual Units Units { get; set; }
        public virtual Units Units1 { get; set; }
    }
}
