//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public Units()
        {
            this.MacroItems = new HashSet<MacroItems>();
            this.PickingItems = new HashSet<PickingItems>();
            this.QuotationDetails = new HashSet<QuotationDetails>();
            this.QuotationTemplateDetails = new HashSet<QuotationTemplateDetails>();
            this.TempQuotationDetails = new HashSet<TempQuotationDetails>();
            this.UnitConverters = new HashSet<UnitConverters>();
            this.UnitConverters1 = new HashSet<UnitConverters>();
            this.ProductionOrderDetails = new HashSet<ProductionOrderDetails>();
            this.ProductionOrderDetails1 = new HashSet<ProductionOrderDetails>();
            this.ProductionOrderDetails2 = new HashSet<ProductionOrderDetails>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MacroItems> MacroItems { get; set; }
        public virtual ICollection<PickingItems> PickingItems { get; set; }
        public virtual ICollection<QuotationDetails> QuotationDetails { get; set; }
        public virtual ICollection<QuotationTemplateDetails> QuotationTemplateDetails { get; set; }
        public virtual ICollection<TempQuotationDetails> TempQuotationDetails { get; set; }
        public virtual ICollection<UnitConverters> UnitConverters { get; set; }
        public virtual ICollection<UnitConverters> UnitConverters1 { get; set; }
        public virtual ICollection<ProductionOrderDetails> ProductionOrderDetails { get; set; }
        public virtual ICollection<ProductionOrderDetails> ProductionOrderDetails1 { get; set; }
        public virtual ICollection<ProductionOrderDetails> ProductionOrderDetails2 { get; set; }
    }
}
