//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AllQuotations
    {
        public int ID { get; set; }
        public Nullable<int> CustomerCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Q1 { get; set; }
        public int Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<int> Q5 { get; set; }
        public Nullable<int> MarkUp { get; set; }
        public Nullable<int> ID_Owner { get; set; }
        public Nullable<int> ID_Approver { get; set; }
        public Nullable<bool> Draft { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> ID_Company { get; set; }
    }
}
