//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EmployeesWorkingDayHours
    {
        public int ID { get; set; }
        public string UniqueName { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public decimal ProductionTime { get; set; }
        public int ID_Phase { get; set; }
        public float RawMaterialX { get; set; }
        public float RawMaterialY { get; set; }
        public float RawMaterialZ { get; set; }
        public string ItemDescription { get; set; }
        public int TypeCode { get; set; }
        public string TypeDescription { get; set; }
        public int ItemTypeCode { get; set; }
        public string ItemTypeDescription { get; set; }
        public string PickingItemOrder { get; set; }
        public Nullable<int> YearProductionDate { get; set; }
        public Nullable<int> MonthProductionDate { get; set; }
        public Nullable<int> ID_ProductionOrder { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ID_Company { get; set; }
    }
}
