//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FreeTypePOD
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> FreeTypeCode { get; set; }
        public string TypeDescription { get; set; }
        public Nullable<int> FreeItemTypeCode { get; set; }
        public string ItemTypeDescription { get; set; }
        public string FreeItemDescription { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> UMRawMaterial { get; set; }
        public string UMDescription { get; set; }
        public Nullable<float> RawMaterialQuantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Note { get; set; }
    }
}
