//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FreeTypePrepare
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public string NumDDT { get; set; }
        public string mm_descr { get; set; }
    }
}
