//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HitsOfMacroItems
    {
        public int ID { get; set; }
        public int TypeCode { get; set; }
        public int ItemTypeCode { get; set; }
        public string MacroItemDescription { get; set; }
        public int UM { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public bool Inserted { get; set; }
        public bool Multiply { get; set; }
        public int Percentage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Link { get; set; }
        public string PILink { get; set; }
        public string Order { get; set; }
        public Nullable<int> Template { get; set; }
        public Nullable<int> ItemManufacturing { get; set; }
        public string Note { get; set; }
        public int Hits { get; set; }
        public Nullable<int> ID_Company { get; set; }
        public bool ExpandInStats { get; set; }
    }
}
