//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MenuItems
    {
        public string ID { get; set; }
        public int TypeCode { get; set; }
        public int ItemTypeCode { get; set; }
        public string ItemDescription { get; set; }
        public bool Inserted { get; set; }
        public string Link { get; set; }
        public string Order { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> ID_Company { get; set; }
    }
}
