//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProductionOrdersCosts
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string PORDescription { get; set; }
        public Nullable<float> StartQuantity { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public Nullable<int> ID_CustomerOrder { get; set; }
        public Nullable<int> ID_Quotation { get; set; }
        public Nullable<decimal> PORDirectCost { get; set; }
        public Nullable<double> PORDetailsCost { get; set; }
        public Nullable<decimal> PORDetailsHistoricalCost { get; set; }
        public decimal PORPrice { get; set; }
        public Nullable<double> ProducedQuantity { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AccountNote { get; set; }
        public Nullable<int> ID_Company { get; set; }
        public string Note { get; set; }
    }
}
