//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PickingItems
    {
        public int ID { get; set; }
        public string TypeDescription { get; set; }
        public string ItemTypeDescription { get; set; }
        public string ItemDescription { get; set; }
        public string UnitDescription { get; set; }
        public bool Inserted { get; set; }
        public bool Multiply { get; set; }
        public decimal Cost { get; set; }
        public int Percentage { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string Order { get; set; }
        public Nullable<int> Template { get; set; }
        public Nullable<int> ItemManufacturing { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int TypeCode { get; set; }
        public int ItemTypeCode { get; set; }
        public Nullable<int> SupplierCode { get; set; }
        public string CompanyDescription { get; set; }
    }
}
