//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabExtimOperator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_QUOPORCostsPrices
    {
        public Nullable<int> ID_Quotation { get; set; }
        public Nullable<int> QUOOwner { get; set; }
        public string OwnerName { get; set; }
        public string QUOSubject { get; set; }
        public Nullable<double> PORSQuantity { get; set; }
        public Nullable<int> PORID_Customer { get; set; }
        public Nullable<double> PORTotCost { get; set; }
        public Nullable<decimal> PORTotHistoricalCost { get; set; }
        public Nullable<double> QUOTotCost { get; set; }
        public Nullable<double> PORSProducedQuantity { get; set; }
        public int ID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AccountNote { get; set; }
        public Nullable<int> IDAgente1 { get; set; }
        public string DescrizioneAgente1 { get; set; }
        public Nullable<decimal> FATTotValue { get; set; }
        public Nullable<decimal> ProvvTotValue { get; set; }
        public Nullable<System.DateTime> DataBolla { get; set; }
        public string TipoRec { get; set; }
        public string PriceCom { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ID_Company { get; set; }
        public string Number { get; set; }
        public string Note { get; set; }
    }
}
