#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLabExtim
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sql_Ep")]
	public partial class Sql_EpDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDB_Ordini(DB_Ordini instance);
    partial void UpdateDB_Ordini(DB_Ordini instance);
    partial void DeleteDB_Ordini(DB_Ordini instance);
    #endregion
		
		public Sql_EpDataContext() : 
				base(global::DLLabExtim.Properties.Settings.Default.Sql_EpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Sql_EpDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sql_EpDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sql_EpDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sql_EpDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DB_Ordini> DB_Ordinis
		{
			get
			{
				return this.GetTable<DB_Ordini>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DB_Ordini")]
	public partial class DB_Ordini : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_ID;
		
		private string _i_Cliente;
		
		private string _i_Codice;
		
		private string _i_o_Ricetta;
		
		private System.Nullable<int> _o_Pezzi;
		
		private System.Nullable<int> _o_FogliIncollati;
		
		private System.Nullable<int> _o_Cartoni;
		
		private System.Nullable<int> _o_Ribordati;
		
		private System.Nullable<int> _o_Scarti;
		
		private string _o_TimeEmergenza;
		
		private string _o_ProdPezzi;
		
		private string _o_TimeArresto;
		
		private string _o_TimeAvviamento;
		
		private string _o_TimeProduzione;
		
		private string _o_TimeRegistrazione;
		
		private System.Nullable<bool> _o_BitEmergenza;
		
		private System.Nullable<bool> _o_BitArresto;
		
		private System.Nullable<int> _i_Quantita;
		
		private System.Nullable<bool> _o_BitAvviamento;
		
		private System.Nullable<bool> _o_BitProduzione;
		
		private string _Articolo;
		
		private string _o_DataInizio;
		
		private string _o_OraInizio;
		
		private string _o_DataFine;
		
		private string _o_OraFine;
		
		private string _Giorno;
		
		private System.Nullable<bool> _Record;
		
		private string _i_o_Sospensione;
		
		private System.Nullable<int> _i_Passaggi;
		
		private System.Nullable<int> _i_Larghezza;
		
		private System.Nullable<int> _i_Lunghezza;
		
		private System.Nullable<int> _o_pezzi_2;
		
		private System.Nullable<int> _o_FogliIncollati_2;
		
		private System.Nullable<int> _o_Cartoni_2;
		
		private System.Nullable<int> _o_Ribordati_2;
		
		private System.Nullable<int> _o_Scarti_2;
		
		private string _o_TimeEmergenza_2;
		
		private string _o_ProdPezzi_2;
		
		private string _o_TimeArresto_2;
		
		private string _o_TimeAvviamento_2;
		
		private string _o_TimeProduzione_2;
		
		private string _o_TimeRegistrazione_2;
		
		private System.Nullable<bool> _o_BitEmergenza_2;
		
		private System.Nullable<bool> _o_BitArresto_2;
		
		private System.Nullable<bool> _o_BitAvviamento_2;
		
		private System.Nullable<bool> _o_BitProduzione_2;
		
		private string _o_DataInizio_2;
		
		private string _o_OraInizio_2;
		
		private string _o_DataFine_2;
		
		private string _o_OraFine_2;
		
		private System.Nullable<int> _i_Larghezza_2;
		
		private System.Nullable<int> _i_Lunghezza_2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_IDChanging(int value);
    partial void Oni_IDChanged();
    partial void Oni_ClienteChanging(string value);
    partial void Oni_ClienteChanged();
    partial void Oni_CodiceChanging(string value);
    partial void Oni_CodiceChanged();
    partial void Oni_o_RicettaChanging(string value);
    partial void Oni_o_RicettaChanged();
    partial void Ono_PezziChanging(System.Nullable<int> value);
    partial void Ono_PezziChanged();
    partial void Ono_FogliIncollatiChanging(System.Nullable<int> value);
    partial void Ono_FogliIncollatiChanged();
    partial void Ono_CartoniChanging(System.Nullable<int> value);
    partial void Ono_CartoniChanged();
    partial void Ono_RibordatiChanging(System.Nullable<int> value);
    partial void Ono_RibordatiChanged();
    partial void Ono_ScartiChanging(System.Nullable<int> value);
    partial void Ono_ScartiChanged();
    partial void Ono_TimeEmergenzaChanging(string value);
    partial void Ono_TimeEmergenzaChanged();
    partial void Ono_ProdPezziChanging(string value);
    partial void Ono_ProdPezziChanged();
    partial void Ono_TimeArrestoChanging(string value);
    partial void Ono_TimeArrestoChanged();
    partial void Ono_TimeAvviamentoChanging(string value);
    partial void Ono_TimeAvviamentoChanged();
    partial void Ono_TimeProduzioneChanging(string value);
    partial void Ono_TimeProduzioneChanged();
    partial void Ono_TimeRegistrazioneChanging(string value);
    partial void Ono_TimeRegistrazioneChanged();
    partial void Ono_BitEmergenzaChanging(System.Nullable<bool> value);
    partial void Ono_BitEmergenzaChanged();
    partial void Ono_BitArrestoChanging(System.Nullable<bool> value);
    partial void Ono_BitArrestoChanged();
    partial void Oni_QuantitaChanging(System.Nullable<int> value);
    partial void Oni_QuantitaChanged();
    partial void Ono_BitAvviamentoChanging(System.Nullable<bool> value);
    partial void Ono_BitAvviamentoChanged();
    partial void Ono_BitProduzioneChanging(System.Nullable<bool> value);
    partial void Ono_BitProduzioneChanged();
    partial void OnArticoloChanging(string value);
    partial void OnArticoloChanged();
    partial void Ono_DataInizioChanging(string value);
    partial void Ono_DataInizioChanged();
    partial void Ono_OraInizioChanging(string value);
    partial void Ono_OraInizioChanged();
    partial void Ono_DataFineChanging(string value);
    partial void Ono_DataFineChanged();
    partial void Ono_OraFineChanging(string value);
    partial void Ono_OraFineChanged();
    partial void OnGiornoChanging(string value);
    partial void OnGiornoChanged();
    partial void OnRecordChanging(System.Nullable<bool> value);
    partial void OnRecordChanged();
    partial void Oni_o_SospensioneChanging(string value);
    partial void Oni_o_SospensioneChanged();
    partial void Oni_PassaggiChanging(System.Nullable<int> value);
    partial void Oni_PassaggiChanged();
    partial void Oni_LarghezzaChanging(System.Nullable<int> value);
    partial void Oni_LarghezzaChanged();
    partial void Oni_LunghezzaChanging(System.Nullable<int> value);
    partial void Oni_LunghezzaChanged();
    partial void Ono_pezzi_2Changing(System.Nullable<int> value);
    partial void Ono_pezzi_2Changed();
    partial void Ono_FogliIncollati_2Changing(System.Nullable<int> value);
    partial void Ono_FogliIncollati_2Changed();
    partial void Ono_Cartoni_2Changing(System.Nullable<int> value);
    partial void Ono_Cartoni_2Changed();
    partial void Ono_Ribordati_2Changing(System.Nullable<int> value);
    partial void Ono_Ribordati_2Changed();
    partial void Ono_Scarti_2Changing(System.Nullable<int> value);
    partial void Ono_Scarti_2Changed();
    partial void Ono_TimeEmergenza_2Changing(string value);
    partial void Ono_TimeEmergenza_2Changed();
    partial void Ono_ProdPezzi_2Changing(string value);
    partial void Ono_ProdPezzi_2Changed();
    partial void Ono_TimeArresto_2Changing(string value);
    partial void Ono_TimeArresto_2Changed();
    partial void Ono_TimeAvviamento_2Changing(string value);
    partial void Ono_TimeAvviamento_2Changed();
    partial void Ono_TimeProduzione_2Changing(string value);
    partial void Ono_TimeProduzione_2Changed();
    partial void Ono_TimeRegistrazione_2Changing(string value);
    partial void Ono_TimeRegistrazione_2Changed();
    partial void Ono_BitEmergenza_2Changing(System.Nullable<bool> value);
    partial void Ono_BitEmergenza_2Changed();
    partial void Ono_BitArresto_2Changing(System.Nullable<bool> value);
    partial void Ono_BitArresto_2Changed();
    partial void Ono_BitAvviamento_2Changing(System.Nullable<bool> value);
    partial void Ono_BitAvviamento_2Changed();
    partial void Ono_BitProduzione_2Changing(System.Nullable<bool> value);
    partial void Ono_BitProduzione_2Changed();
    partial void Ono_DataInizio_2Changing(string value);
    partial void Ono_DataInizio_2Changed();
    partial void Ono_OraInizio_2Changing(string value);
    partial void Ono_OraInizio_2Changed();
    partial void Ono_DataFine_2Changing(string value);
    partial void Ono_DataFine_2Changed();
    partial void Ono_OraFine_2Changing(string value);
    partial void Ono_OraFine_2Changed();
    partial void Oni_Larghezza_2Changing(System.Nullable<int> value);
    partial void Oni_Larghezza_2Changed();
    partial void Oni_Lunghezza_2Changing(System.Nullable<int> value);
    partial void Oni_Lunghezza_2Changed();
    #endregion
		
		public DB_Ordini()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int i_ID
		{
			get
			{
				return this._i_ID;
			}
			set
			{
				if ((this._i_ID != value))
				{
					this.Oni_IDChanging(value);
					this.SendPropertyChanging();
					this._i_ID = value;
					this.SendPropertyChanged("i_ID");
					this.Oni_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Cliente", DbType="NVarChar(50)")]
		public string i_Cliente
		{
			get
			{
				return this._i_Cliente;
			}
			set
			{
				if ((this._i_Cliente != value))
				{
					this.Oni_ClienteChanging(value);
					this.SendPropertyChanging();
					this._i_Cliente = value;
					this.SendPropertyChanged("i_Cliente");
					this.Oni_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Codice", DbType="NVarChar(50)")]
		public string i_Codice
		{
			get
			{
				return this._i_Codice;
			}
			set
			{
				if ((this._i_Codice != value))
				{
					this.Oni_CodiceChanging(value);
					this.SendPropertyChanging();
					this._i_Codice = value;
					this.SendPropertyChanged("i_Codice");
					this.Oni_CodiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_o_Ricetta", DbType="NVarChar(50)")]
		public string i_o_Ricetta
		{
			get
			{
				return this._i_o_Ricetta;
			}
			set
			{
				if ((this._i_o_Ricetta != value))
				{
					this.Oni_o_RicettaChanging(value);
					this.SendPropertyChanging();
					this._i_o_Ricetta = value;
					this.SendPropertyChanged("i_o_Ricetta");
					this.Oni_o_RicettaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_Pezzi", DbType="Int")]
		public System.Nullable<int> o_Pezzi
		{
			get
			{
				return this._o_Pezzi;
			}
			set
			{
				if ((this._o_Pezzi != value))
				{
					this.Ono_PezziChanging(value);
					this.SendPropertyChanging();
					this._o_Pezzi = value;
					this.SendPropertyChanged("o_Pezzi");
					this.Ono_PezziChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_FogliIncollati", DbType="Int")]
		public System.Nullable<int> o_FogliIncollati
		{
			get
			{
				return this._o_FogliIncollati;
			}
			set
			{
				if ((this._o_FogliIncollati != value))
				{
					this.Ono_FogliIncollatiChanging(value);
					this.SendPropertyChanging();
					this._o_FogliIncollati = value;
					this.SendPropertyChanged("o_FogliIncollati");
					this.Ono_FogliIncollatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_Cartoni", DbType="Int")]
		public System.Nullable<int> o_Cartoni
		{
			get
			{
				return this._o_Cartoni;
			}
			set
			{
				if ((this._o_Cartoni != value))
				{
					this.Ono_CartoniChanging(value);
					this.SendPropertyChanging();
					this._o_Cartoni = value;
					this.SendPropertyChanged("o_Cartoni");
					this.Ono_CartoniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_Ribordati", DbType="Int")]
		public System.Nullable<int> o_Ribordati
		{
			get
			{
				return this._o_Ribordati;
			}
			set
			{
				if ((this._o_Ribordati != value))
				{
					this.Ono_RibordatiChanging(value);
					this.SendPropertyChanging();
					this._o_Ribordati = value;
					this.SendPropertyChanged("o_Ribordati");
					this.Ono_RibordatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_Scarti", DbType="Int")]
		public System.Nullable<int> o_Scarti
		{
			get
			{
				return this._o_Scarti;
			}
			set
			{
				if ((this._o_Scarti != value))
				{
					this.Ono_ScartiChanging(value);
					this.SendPropertyChanging();
					this._o_Scarti = value;
					this.SendPropertyChanged("o_Scarti");
					this.Ono_ScartiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeEmergenza", DbType="NVarChar(50)")]
		public string o_TimeEmergenza
		{
			get
			{
				return this._o_TimeEmergenza;
			}
			set
			{
				if ((this._o_TimeEmergenza != value))
				{
					this.Ono_TimeEmergenzaChanging(value);
					this.SendPropertyChanging();
					this._o_TimeEmergenza = value;
					this.SendPropertyChanged("o_TimeEmergenza");
					this.Ono_TimeEmergenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_ProdPezzi", DbType="NVarChar(50)")]
		public string o_ProdPezzi
		{
			get
			{
				return this._o_ProdPezzi;
			}
			set
			{
				if ((this._o_ProdPezzi != value))
				{
					this.Ono_ProdPezziChanging(value);
					this.SendPropertyChanging();
					this._o_ProdPezzi = value;
					this.SendPropertyChanged("o_ProdPezzi");
					this.Ono_ProdPezziChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeArresto", DbType="NVarChar(50)")]
		public string o_TimeArresto
		{
			get
			{
				return this._o_TimeArresto;
			}
			set
			{
				if ((this._o_TimeArresto != value))
				{
					this.Ono_TimeArrestoChanging(value);
					this.SendPropertyChanging();
					this._o_TimeArresto = value;
					this.SendPropertyChanged("o_TimeArresto");
					this.Ono_TimeArrestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeAvviamento", DbType="NVarChar(50)")]
		public string o_TimeAvviamento
		{
			get
			{
				return this._o_TimeAvviamento;
			}
			set
			{
				if ((this._o_TimeAvviamento != value))
				{
					this.Ono_TimeAvviamentoChanging(value);
					this.SendPropertyChanging();
					this._o_TimeAvviamento = value;
					this.SendPropertyChanged("o_TimeAvviamento");
					this.Ono_TimeAvviamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeProduzione", DbType="NVarChar(50)")]
		public string o_TimeProduzione
		{
			get
			{
				return this._o_TimeProduzione;
			}
			set
			{
				if ((this._o_TimeProduzione != value))
				{
					this.Ono_TimeProduzioneChanging(value);
					this.SendPropertyChanging();
					this._o_TimeProduzione = value;
					this.SendPropertyChanged("o_TimeProduzione");
					this.Ono_TimeProduzioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeRegistrazione", DbType="NVarChar(50)")]
		public string o_TimeRegistrazione
		{
			get
			{
				return this._o_TimeRegistrazione;
			}
			set
			{
				if ((this._o_TimeRegistrazione != value))
				{
					this.Ono_TimeRegistrazioneChanging(value);
					this.SendPropertyChanging();
					this._o_TimeRegistrazione = value;
					this.SendPropertyChanged("o_TimeRegistrazione");
					this.Ono_TimeRegistrazioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitEmergenza", DbType="Bit")]
		public System.Nullable<bool> o_BitEmergenza
		{
			get
			{
				return this._o_BitEmergenza;
			}
			set
			{
				if ((this._o_BitEmergenza != value))
				{
					this.Ono_BitEmergenzaChanging(value);
					this.SendPropertyChanging();
					this._o_BitEmergenza = value;
					this.SendPropertyChanged("o_BitEmergenza");
					this.Ono_BitEmergenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitArresto", DbType="Bit")]
		public System.Nullable<bool> o_BitArresto
		{
			get
			{
				return this._o_BitArresto;
			}
			set
			{
				if ((this._o_BitArresto != value))
				{
					this.Ono_BitArrestoChanging(value);
					this.SendPropertyChanging();
					this._o_BitArresto = value;
					this.SendPropertyChanged("o_BitArresto");
					this.Ono_BitArrestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Quantita", DbType="Int")]
		public System.Nullable<int> i_Quantita
		{
			get
			{
				return this._i_Quantita;
			}
			set
			{
				if ((this._i_Quantita != value))
				{
					this.Oni_QuantitaChanging(value);
					this.SendPropertyChanging();
					this._i_Quantita = value;
					this.SendPropertyChanged("i_Quantita");
					this.Oni_QuantitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitAvviamento", DbType="Bit")]
		public System.Nullable<bool> o_BitAvviamento
		{
			get
			{
				return this._o_BitAvviamento;
			}
			set
			{
				if ((this._o_BitAvviamento != value))
				{
					this.Ono_BitAvviamentoChanging(value);
					this.SendPropertyChanging();
					this._o_BitAvviamento = value;
					this.SendPropertyChanged("o_BitAvviamento");
					this.Ono_BitAvviamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitProduzione", DbType="Bit")]
		public System.Nullable<bool> o_BitProduzione
		{
			get
			{
				return this._o_BitProduzione;
			}
			set
			{
				if ((this._o_BitProduzione != value))
				{
					this.Ono_BitProduzioneChanging(value);
					this.SendPropertyChanging();
					this._o_BitProduzione = value;
					this.SendPropertyChanged("o_BitProduzione");
					this.Ono_BitProduzioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Articolo", DbType="NChar(50)")]
		public string Articolo
		{
			get
			{
				return this._Articolo;
			}
			set
			{
				if ((this._Articolo != value))
				{
					this.OnArticoloChanging(value);
					this.SendPropertyChanging();
					this._Articolo = value;
					this.SendPropertyChanged("Articolo");
					this.OnArticoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_DataInizio", DbType="NVarChar(50)")]
		public string o_DataInizio
		{
			get
			{
				return this._o_DataInizio;
			}
			set
			{
				if ((this._o_DataInizio != value))
				{
					this.Ono_DataInizioChanging(value);
					this.SendPropertyChanging();
					this._o_DataInizio = value;
					this.SendPropertyChanged("o_DataInizio");
					this.Ono_DataInizioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_OraInizio", DbType="NVarChar(50)")]
		public string o_OraInizio
		{
			get
			{
				return this._o_OraInizio;
			}
			set
			{
				if ((this._o_OraInizio != value))
				{
					this.Ono_OraInizioChanging(value);
					this.SendPropertyChanging();
					this._o_OraInizio = value;
					this.SendPropertyChanged("o_OraInizio");
					this.Ono_OraInizioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_DataFine", DbType="NVarChar(50)")]
		public string o_DataFine
		{
			get
			{
				return this._o_DataFine;
			}
			set
			{
				if ((this._o_DataFine != value))
				{
					this.Ono_DataFineChanging(value);
					this.SendPropertyChanging();
					this._o_DataFine = value;
					this.SendPropertyChanged("o_DataFine");
					this.Ono_DataFineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_OraFine", DbType="NVarChar(50)")]
		public string o_OraFine
		{
			get
			{
				return this._o_OraFine;
			}
			set
			{
				if ((this._o_OraFine != value))
				{
					this.Ono_OraFineChanging(value);
					this.SendPropertyChanging();
					this._o_OraFine = value;
					this.SendPropertyChanged("o_OraFine");
					this.Ono_OraFineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giorno", DbType="NVarChar(50)")]
		public string Giorno
		{
			get
			{
				return this._Giorno;
			}
			set
			{
				if ((this._Giorno != value))
				{
					this.OnGiornoChanging(value);
					this.SendPropertyChanging();
					this._Giorno = value;
					this.SendPropertyChanged("Giorno");
					this.OnGiornoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Record", DbType="Bit")]
		public System.Nullable<bool> Record
		{
			get
			{
				return this._Record;
			}
			set
			{
				if ((this._Record != value))
				{
					this.OnRecordChanging(value);
					this.SendPropertyChanging();
					this._Record = value;
					this.SendPropertyChanged("Record");
					this.OnRecordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_o_Sospensione", DbType="NVarChar(50)")]
		public string i_o_Sospensione
		{
			get
			{
				return this._i_o_Sospensione;
			}
			set
			{
				if ((this._i_o_Sospensione != value))
				{
					this.Oni_o_SospensioneChanging(value);
					this.SendPropertyChanging();
					this._i_o_Sospensione = value;
					this.SendPropertyChanged("i_o_Sospensione");
					this.Oni_o_SospensioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Passaggi", DbType="Int")]
		public System.Nullable<int> i_Passaggi
		{
			get
			{
				return this._i_Passaggi;
			}
			set
			{
				if ((this._i_Passaggi != value))
				{
					this.Oni_PassaggiChanging(value);
					this.SendPropertyChanging();
					this._i_Passaggi = value;
					this.SendPropertyChanged("i_Passaggi");
					this.Oni_PassaggiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Larghezza", DbType="Int")]
		public System.Nullable<int> i_Larghezza
		{
			get
			{
				return this._i_Larghezza;
			}
			set
			{
				if ((this._i_Larghezza != value))
				{
					this.Oni_LarghezzaChanging(value);
					this.SendPropertyChanging();
					this._i_Larghezza = value;
					this.SendPropertyChanged("i_Larghezza");
					this.Oni_LarghezzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Lunghezza", DbType="Int")]
		public System.Nullable<int> i_Lunghezza
		{
			get
			{
				return this._i_Lunghezza;
			}
			set
			{
				if ((this._i_Lunghezza != value))
				{
					this.Oni_LunghezzaChanging(value);
					this.SendPropertyChanging();
					this._i_Lunghezza = value;
					this.SendPropertyChanged("i_Lunghezza");
					this.Oni_LunghezzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_pezzi_2", DbType="Int")]
		public System.Nullable<int> o_pezzi_2
		{
			get
			{
				return this._o_pezzi_2;
			}
			set
			{
				if ((this._o_pezzi_2 != value))
				{
					this.Ono_pezzi_2Changing(value);
					this.SendPropertyChanging();
					this._o_pezzi_2 = value;
					this.SendPropertyChanged("o_pezzi_2");
					this.Ono_pezzi_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_FogliIncollati_2", DbType="Int")]
		public System.Nullable<int> o_FogliIncollati_2
		{
			get
			{
				return this._o_FogliIncollati_2;
			}
			set
			{
				if ((this._o_FogliIncollati_2 != value))
				{
					this.Ono_FogliIncollati_2Changing(value);
					this.SendPropertyChanging();
					this._o_FogliIncollati_2 = value;
					this.SendPropertyChanged("o_FogliIncollati_2");
					this.Ono_FogliIncollati_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_Cartoni_2", DbType="Int")]
		public System.Nullable<int> o_Cartoni_2
		{
			get
			{
				return this._o_Cartoni_2;
			}
			set
			{
				if ((this._o_Cartoni_2 != value))
				{
					this.Ono_Cartoni_2Changing(value);
					this.SendPropertyChanging();
					this._o_Cartoni_2 = value;
					this.SendPropertyChanged("o_Cartoni_2");
					this.Ono_Cartoni_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_Ribordati_2", DbType="Int")]
		public System.Nullable<int> o_Ribordati_2
		{
			get
			{
				return this._o_Ribordati_2;
			}
			set
			{
				if ((this._o_Ribordati_2 != value))
				{
					this.Ono_Ribordati_2Changing(value);
					this.SendPropertyChanging();
					this._o_Ribordati_2 = value;
					this.SendPropertyChanged("o_Ribordati_2");
					this.Ono_Ribordati_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_Scarti_2", DbType="Int")]
		public System.Nullable<int> o_Scarti_2
		{
			get
			{
				return this._o_Scarti_2;
			}
			set
			{
				if ((this._o_Scarti_2 != value))
				{
					this.Ono_Scarti_2Changing(value);
					this.SendPropertyChanging();
					this._o_Scarti_2 = value;
					this.SendPropertyChanged("o_Scarti_2");
					this.Ono_Scarti_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeEmergenza_2", DbType="NVarChar(50)")]
		public string o_TimeEmergenza_2
		{
			get
			{
				return this._o_TimeEmergenza_2;
			}
			set
			{
				if ((this._o_TimeEmergenza_2 != value))
				{
					this.Ono_TimeEmergenza_2Changing(value);
					this.SendPropertyChanging();
					this._o_TimeEmergenza_2 = value;
					this.SendPropertyChanged("o_TimeEmergenza_2");
					this.Ono_TimeEmergenza_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_ProdPezzi_2", DbType="NVarChar(50)")]
		public string o_ProdPezzi_2
		{
			get
			{
				return this._o_ProdPezzi_2;
			}
			set
			{
				if ((this._o_ProdPezzi_2 != value))
				{
					this.Ono_ProdPezzi_2Changing(value);
					this.SendPropertyChanging();
					this._o_ProdPezzi_2 = value;
					this.SendPropertyChanged("o_ProdPezzi_2");
					this.Ono_ProdPezzi_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeArresto_2", DbType="NVarChar(50)")]
		public string o_TimeArresto_2
		{
			get
			{
				return this._o_TimeArresto_2;
			}
			set
			{
				if ((this._o_TimeArresto_2 != value))
				{
					this.Ono_TimeArresto_2Changing(value);
					this.SendPropertyChanging();
					this._o_TimeArresto_2 = value;
					this.SendPropertyChanged("o_TimeArresto_2");
					this.Ono_TimeArresto_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeAvviamento_2", DbType="NVarChar(50)")]
		public string o_TimeAvviamento_2
		{
			get
			{
				return this._o_TimeAvviamento_2;
			}
			set
			{
				if ((this._o_TimeAvviamento_2 != value))
				{
					this.Ono_TimeAvviamento_2Changing(value);
					this.SendPropertyChanging();
					this._o_TimeAvviamento_2 = value;
					this.SendPropertyChanged("o_TimeAvviamento_2");
					this.Ono_TimeAvviamento_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeProduzione_2", DbType="NVarChar(50)")]
		public string o_TimeProduzione_2
		{
			get
			{
				return this._o_TimeProduzione_2;
			}
			set
			{
				if ((this._o_TimeProduzione_2 != value))
				{
					this.Ono_TimeProduzione_2Changing(value);
					this.SendPropertyChanging();
					this._o_TimeProduzione_2 = value;
					this.SendPropertyChanged("o_TimeProduzione_2");
					this.Ono_TimeProduzione_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_TimeRegistrazione_2", DbType="NVarChar(50)")]
		public string o_TimeRegistrazione_2
		{
			get
			{
				return this._o_TimeRegistrazione_2;
			}
			set
			{
				if ((this._o_TimeRegistrazione_2 != value))
				{
					this.Ono_TimeRegistrazione_2Changing(value);
					this.SendPropertyChanging();
					this._o_TimeRegistrazione_2 = value;
					this.SendPropertyChanged("o_TimeRegistrazione_2");
					this.Ono_TimeRegistrazione_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitEmergenza_2", DbType="Bit")]
		public System.Nullable<bool> o_BitEmergenza_2
		{
			get
			{
				return this._o_BitEmergenza_2;
			}
			set
			{
				if ((this._o_BitEmergenza_2 != value))
				{
					this.Ono_BitEmergenza_2Changing(value);
					this.SendPropertyChanging();
					this._o_BitEmergenza_2 = value;
					this.SendPropertyChanged("o_BitEmergenza_2");
					this.Ono_BitEmergenza_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitArresto_2", DbType="Bit")]
		public System.Nullable<bool> o_BitArresto_2
		{
			get
			{
				return this._o_BitArresto_2;
			}
			set
			{
				if ((this._o_BitArresto_2 != value))
				{
					this.Ono_BitArresto_2Changing(value);
					this.SendPropertyChanging();
					this._o_BitArresto_2 = value;
					this.SendPropertyChanged("o_BitArresto_2");
					this.Ono_BitArresto_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitAvviamento_2", DbType="Bit")]
		public System.Nullable<bool> o_BitAvviamento_2
		{
			get
			{
				return this._o_BitAvviamento_2;
			}
			set
			{
				if ((this._o_BitAvviamento_2 != value))
				{
					this.Ono_BitAvviamento_2Changing(value);
					this.SendPropertyChanging();
					this._o_BitAvviamento_2 = value;
					this.SendPropertyChanged("o_BitAvviamento_2");
					this.Ono_BitAvviamento_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_BitProduzione_2", DbType="Bit")]
		public System.Nullable<bool> o_BitProduzione_2
		{
			get
			{
				return this._o_BitProduzione_2;
			}
			set
			{
				if ((this._o_BitProduzione_2 != value))
				{
					this.Ono_BitProduzione_2Changing(value);
					this.SendPropertyChanging();
					this._o_BitProduzione_2 = value;
					this.SendPropertyChanged("o_BitProduzione_2");
					this.Ono_BitProduzione_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_DataInizio_2", DbType="NVarChar(50)")]
		public string o_DataInizio_2
		{
			get
			{
				return this._o_DataInizio_2;
			}
			set
			{
				if ((this._o_DataInizio_2 != value))
				{
					this.Ono_DataInizio_2Changing(value);
					this.SendPropertyChanging();
					this._o_DataInizio_2 = value;
					this.SendPropertyChanged("o_DataInizio_2");
					this.Ono_DataInizio_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_OraInizio_2", DbType="NVarChar(50)")]
		public string o_OraInizio_2
		{
			get
			{
				return this._o_OraInizio_2;
			}
			set
			{
				if ((this._o_OraInizio_2 != value))
				{
					this.Ono_OraInizio_2Changing(value);
					this.SendPropertyChanging();
					this._o_OraInizio_2 = value;
					this.SendPropertyChanged("o_OraInizio_2");
					this.Ono_OraInizio_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_DataFine_2", DbType="NVarChar(50)")]
		public string o_DataFine_2
		{
			get
			{
				return this._o_DataFine_2;
			}
			set
			{
				if ((this._o_DataFine_2 != value))
				{
					this.Ono_DataFine_2Changing(value);
					this.SendPropertyChanging();
					this._o_DataFine_2 = value;
					this.SendPropertyChanged("o_DataFine_2");
					this.Ono_DataFine_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_OraFine_2", DbType="NVarChar(50)")]
		public string o_OraFine_2
		{
			get
			{
				return this._o_OraFine_2;
			}
			set
			{
				if ((this._o_OraFine_2 != value))
				{
					this.Ono_OraFine_2Changing(value);
					this.SendPropertyChanging();
					this._o_OraFine_2 = value;
					this.SendPropertyChanged("o_OraFine_2");
					this.Ono_OraFine_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Larghezza_2", DbType="Int")]
		public System.Nullable<int> i_Larghezza_2
		{
			get
			{
				return this._i_Larghezza_2;
			}
			set
			{
				if ((this._i_Larghezza_2 != value))
				{
					this.Oni_Larghezza_2Changing(value);
					this.SendPropertyChanging();
					this._i_Larghezza_2 = value;
					this.SendPropertyChanged("i_Larghezza_2");
					this.Oni_Larghezza_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_Lunghezza_2", DbType="Int")]
		public System.Nullable<int> i_Lunghezza_2
		{
			get
			{
				return this._i_Lunghezza_2;
			}
			set
			{
				if ((this._i_Lunghezza_2 != value))
				{
					this.Oni_Lunghezza_2Changing(value);
					this.SendPropertyChanging();
					this._i_Lunghezza_2 = value;
					this.SendPropertyChanged("i_Lunghezza_2");
					this.Oni_Lunghezza_2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
