//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLLabExtim.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=LABE;Integrated Security=Tru" +
            "e")]
        public string GestConnectionString {
            get {
                return ((string)(this["GestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=LabExtim;Integrated Security" +
            "=True")]
        public string LabExtimConnectionString {
            get {
                return ((string)(this["LabExtimConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=LabExtim;Integrated Security" +
            "=True")]
        public string LabExtimConnectionString1 {
            get {
                return ((string)(this["LabExtimConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=ASPNETDB;Integrated Security" +
            "=True")]
        public string ASPNETDBConnectionString {
            get {
                return ((string)(this["ASPNETDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=LabExtim;Integrated Security" +
            "=True")]
        public string LabExtimConnectionString2 {
            get {
                return ((string)(this["LabExtimConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=LabExtim;Integrated Security" +
            "=True")]
        public string LabExtimConnectionString3 {
            get {
                return ((string)(this["LabExtimConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=LabExtim;Integrated Security" +
            "=True")]
        public string LabExtimConnectionString4 {
            get {
                return ((string)(this["LabExtimConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=labextim;Integrated Security" +
            "=True")]
        public string labextimConnectionString5 {
            get {
                return ((string)(this["labextimConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMBINARIO-NIK\\SQL2008R2;Initial Catalog=LabExtim;Integrated Security" +
            "=True")]
        public string LabExtimConnectionString6 {
            get {
                return ((string)(this["LabExtimConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=LabExtim;Persist Security Info=True;User ID=usrw")]
        public string LabExtimConnectionString7 {
            get {
                return ((string)(this["LabExtimConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=LabExtim;Persist Security Info=True;User ID=usrw;Mu" +
            "ltipleActiveResultSets=True;Application Name=EntityFramework")]
        public string LabExtimConnectionString8 {
            get {
                return ((string)(this["LabExtimConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=LabExtim;User ID=usrw;Password=usrw")]
        public string LabExtimConnectionString9 {
            get {
                return ((string)(this["LabExtimConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=LabExtim;Integrated Security=True")]
        public string LabExtimConnectionString10 {
            get {
                return ((string)(this["LabExtimConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE.LABE.LOCAL;Initial Catalog=LabExtim;Persist Security Info=Tr" +
            "ue;User ID=sa")]
        public string LabExtimConnectionString11 {
            get {
                return ((string)(this["LabExtimConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATANEW.LABE.LOCAL;Initial Catalog=LabExtim;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string LabExtimConnectionString12 {
            get {
                return ((string)(this["LabExtimConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.193;Initial Catalog=Sql_Ep;User ID=Cartolabe;Password=P@ssw" +
            "ord1")]
        public string Sql_EpConnectionString {
            get {
                return ((string)(this["Sql_EpConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE;Initial Catalog=LabExtim;Persist Security Info=True;User ID=" +
            "usrw")]
        public string LabExtimConnectionString13 {
            get {
                return ((string)(this["LabExtimConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE;Initial Catalog=LabExtim;Persist Security Info=True;User ID=" +
            "usrw;Password=usrw")]
        public string LabExtimConnectionString14 {
            get {
                return ((string)(this["LabExtimConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE.LABE.LOCAL;Initial Catalog=LabExtim;Persist Security Info=Tr" +
            "ue;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string LabExtimConnectionString15 {
            get {
                return ((string)(this["LabExtimConnectionString15"]));
            }
        }
    }
}
